[package]
name = "moneymarket"
version = "0.3.1"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Common helpers for other moneymarket specs"
license = "Apache-2.0"
repository = "https://github.com/anchor-protocol/money-market-contracts"
homepage = "https://terra.money"
documentation = "https://docs.terra.money"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
interface = ["dep:cw-orch"]

[dependencies]
cw20 = "0.15.1"
cosmwasm-std = "1.1.0"
cosmwasm-schema = "1.1.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

strum = "0.24.1"
strum_macros = "0.24.1"
cw-orch = { version = "0.16.4", optional = true }


[dev-dependencies]

[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true
