[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
# cavern-lsd-wrapper-interface = { version = "0.1.0", package = "interface", git = "https://github.com/cavernperson/cavern-lsd-wrapper" }

cavern-lsd-wrapper-interface = { version = "0.1.0", path = "../../cavern-lsd-wrapper/interface" }
cavern-moneymarket-interface = { version = "0.1.0", path = "../interface" }
cw-orch = { package = "cw-orch-interchain", git = "https://github.com/AbstractSDK/cw-orch-interchain", features = [
    "daemon",
] }
cw-orch-clone-testing = { git = "https://github.com/AbstractSDK/cw-orch-interchain" }

anyhow = { version = "1.0.75", features = ["backtrace"] }
cw-plus-interface = { package = "abstract-cw-plus-interface", git = "https://github.com/abstractsdk/cw-plus" }
cw20-base = { package = "abstract-cw20-base", git = "https://github.com/abstractsdk/cw-plus" }
pretty_env_logger = "0.5.0"
moneymarket = { version = "0.3.1", path = "../packages/moneymarket", features = [
    "interface",
] }
dotenv = "0.15.0"
cosmwasm-std = "1.5.0"
log = "0.4.20"
cosmrs = "0.15.0"
ibc-deposit = { version = "0.1.0", path = "../contracts/ibc-deposit" }
terra-proto-rs = "5.2.0"
serde_json = "1.0.116"
serde = "1.0.198"
cosmwasm-schema = "1.5.0"
